### ISSUE TITLE
"Could not find driver" pop up on the registration page after install

### ISSUE THREAD

**Issue by 4abhinavjain** [YunoHost-Apps/lxd-dashboard_ynh#19]
### Describe the bug

"Could not find driver" pop up on the registration page after install

### Context

- Hardware: *VPS bought online /*
- YunoHost version: 11.2.9.1 (Yunohost installed within a LXC container on Ubuntu 22.04 host)
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- Installing LXD-dashboard on a fresh yunohost instance via GUI

### Logs

*Nothing in error.logs*
*Not able to proceed with LXD Dashboard*

![image](https://github.com/YunoHost-Apps/lxd-dashboard_ynh/assets/34500467/4e3b9c2f-763a-4cd8-946b-36d4d7e9ae21)

**Comment by valterbarreira** [comment]
i also have this problem, why do we have this registration screen when during setup was asked for a admin user and password?

**Comment by 4abhinavjain** [comment]
The latest version from last week (3.8.0) is broken.

I manually install the old October 23 commit from cli using

`yunohost app install https://github.com/YunoHost-Apps/lxd-dashboard_ynh/tree/933699bfd3b8a0c050d1caaa3d3323627f389f15`

Then it install and works fine and no registration details are asked and works with the supplied admin credentials. But if I upgrade it from yunohost GUI (i.e, the latest version) then it is broken again.

I suspect it has to be upgrading the package to php8, but I am not a developer so can't debug. For now, one can use the older branch (command above) to continue using it.

**Comment by kay0u** [comment]
https://github.com/YunoHost-Apps/lxd-dashboard_ynh/pull/20 should fix this issue

**Comment by janbaum** [comment]
Just installed LXD-Dashboard and encountered the same issue.

I setup a LXC container as described [here](https://lxdware.com/installing-the-lxd-dashboard-in-an-lxc-container-v2-x-x/) with adjustments to the version numbers (v3.8.0) and latest Ubuntu 22.04

I installed php7.4 manually.

Exact same error as described above.

EDIT: Container is setup with Ubuntu 22.04, not 24.04
